hooks:
  'before:init':
    - 'npm test'
    - 'npm run clean'
    - 'npm run build'
git:
  commitMessage: "chore(release): v${version}"
  requireCommits: false
github:
  release: false
  #releaseName: "${version}"
  #draft: true
npm:
  release: true
